### ISSUE TITLE
'Failed request /api/contact_message_post//. Message: HMAC authentication key and signature was given, but they are invalid.. Error Code: 41."

### ISSUE THREAD

**Issue by niceonne** [aabiryukov/LocalBitcoinsApi#4]
Can you tell me if this if because of your code, or do I have to contact the localbitcoin support?

**Comment by aabiryukov** [comment]
Code is works successfully. An error occurs when incorrect key or secret.
Check the key and secret that you give into API, or try to generate the new keys.

**Comment by niceonne** [comment]
Yes I got it, in localbticoins dashboard I have to choose multiple permission in the associated key, I only was choosing one key. thank you anyway, btw when will you put the rest of the docs in the api like /api/mark_contact_verified and that stuff? I saw you forget those

**Comment by aabiryukov** [comment]
I add methods gradually, in the fist place most usefull and required methods. Create separete issue to add required API methods.
