### ISSUE TITLE
не работает метод

### ISSUE THREAD

**Issue by sharpgraf** [aabiryukov/LocalBitcoinsApi#5]
Привет, спасибо за api, очень удобно сделано, но у меня не работает метод GetAdList(IEnumerable<string> adList).
Код ошибки такой : Message: HMAC authentication key and signature was given, but they are invalid.. Error Code: 41.
hmac конечно же верный, в чем может быть проблема?)

**Comment by aabiryukov** [comment]
Проверь, какие права выданы этому ключу. Возможно не хватает прав.

**Comment by sharpgraf** [comment]
все права выдал, увы нет. Может в коде, что не так?)
```
            List<string> list = new List<string>
            {
                "720585",
                "400347"
            };
           
            Console.WriteLine(lBCApi.GetAdList(list));
```

**Comment by sharpgraf** [comment]
оказалось, что я использовал старую версию вашего api,  которую я постепенно изучаю, а метод
 GetAdList(IEnumerable adList). я взял с 1.4 версии библиотеки. Точно не разобрался почему так вышло еще)

**Comment by aabiryukov** [comment]
Ок. Тогда закрываю ишью.
