### ISSUE TITLE
TaskCanceledException: A task was canceled.

### ISSUE THREAD

**Issue by sharpgraf** [aabiryukov/LocalBitcoinsApi#7]
Привет! Переодически ловлю TaskCanceledException: A task was canceled. Причем вроде, чем больше таймаут, тем дольше ожидается TaskCanceledException: A task was canceled
В чем может быть проблема?
![image](https://user-images.githubusercontent.com/22218675/41477977-b4181022-70ce-11e8-9bf0-81239a81635b.png)

**Comment by aabiryukov** [comment]
Сервер иногда долго отвечает, поэтому истекает timeout ожидания и возникает TaskCanceledException. Чем больше timeout, тем дольше API ждет ответа от сервера.

**Comment by sharpgraf** [comment]
Как же с этим лучше бороться?) Увеличивать timeout наверно не лучшая практика, потому что сервер может вообще не ответить, подскажите пожалуйста, как лучше обрабатывать такие ошибки

**Comment by aabiryukov** [comment]
Да, делать очень большой таймаут плохой вариант.
Для операций получения данных можно повторять вызов, в случае ошибки.

**Comment by sharpgraf** [comment]
спасибо, а в случае api запросов с разрешением money? В частности /api/wallet-send/ ? Как лучше поступить в случае отсутствия ответа со стороны localbitcoins? Повторять запрос  в этом случае уже не стоит наверное?)

**Comment by aabiryukov** [comment]
В случае таких как wallet-send, операция могла пройти, но сервер не успел ответить, поэтому повторять опасно.
По хорошему, нужно сперва проверить, прошла ли операция (например запросить баланс/историю), если не прошла, то можно безопасно повторять операцию.

P.S.
Я в основном использовал этот API только на чтение, поэтому особенности работы сервиса на операциях записи не исследовал.

**Comment by sharpgraf** [comment]
Спасибо, благодарю за ответ)
